# Compose 版本 Version 2支持更多的指令。Version 1将来会被弃用。
version: "3.9"

networks:
  inner:                # 自定义网络
    name: network_inner # 指定一个自定义网络名称，而不是生成的默认名称。
    driver: bridge 
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1     #网关地址

services:

  redis:
    container_name: rd_redis    # 指定一个自定义容器名称，而不是生成的默认名称。
    image: boiling/redis:latest # 服务的镜像名称或镜像ID。如果镜像在本地不存在，Compose将会尝试拉取镜像
    restart: always
    cap_add:
      - ALL
    ports:        # 配置端口 
      - 6379:6379 # 配置端口 - "宿主机端口:容器暴露端口"
    environment:  # 添加环境变量
      TIME_ZONE: Asia/Shanghai  # 时区
    volumes:      # 挂载外置配置文件
      - "./conf/redis.conf:/etc/redis/redis.conf"
      - "./data:/data"
    networks:
      inner:
        aliases:
           - REDIS_URL
    command: redis-server --port 6379 --requirepass redis --appendonly yes