# Compose 版本 Version 2支持更多的指令
version: "3.9"

services:
  mariadb:
    container_name: rd_mariadb
    image: boiling/mariadb:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    # 添加环境变量
    environment:
      # root 密码
      MARIADB_ROOT_PASSWORD: root
      # root 允许登录的host
      MYSQL_ROOT_HOST: '%'
      # 时区
      TIME_ZONE: Asia/Shanghai
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/rendu-env/dockers/mariadb/conf:/etc/mysql/conf.d"
      - "/rendu-env/dockers/mariadb/logs:/var/log/mysql"
      - "/rendu-env/dockers/mariadb/data:/var/lib/mysql"
      # - "/rendu-env/dockers/mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      inner:
        ipv4_address: 172.16.0.11
    #     ipv6_address: 2001:3984:3989::10
    #   outer:
    #     ipv4_address: 172.18.0.11
    #     ipv6_address: 2001:3984:3989::10
    #     aliases:
    #       - MYSQL_URL
 
    # command: --init-file /docker-entrypoint-initdb.d/init.sql
    privileged: true

    
networks:
  inner:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
      # - subnet: "2001:3984:3989::/64"