# Compose 版本 Version 2支持更多的指令
version: "3.9"

networks:
  inner:  #自定义网络
    name: network_inner # 指定一个自定义网络名称，而不是生成的默认名称。
    driver: bridge 
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1 #网关地址

services:

  mariadb:
    container_name: rd_mariadb
    image: boiling/mariadb:latest
    restart: always
    cap_add:
      - ALL
    ports:
      - 3306:3306
    environment:  # 添加环境变量
      MARIADB_ROOT_PASSWORD: root # root 密码
      MYSQL_ROOT_HOST: '%'  # root 允许登录的host
      TIME_ZONE: Asia/Shanghai  # 时区
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./conf:/etc/mysql/conf.d"
      - "./logs:/var/log/mysql"
      - "./data:/var/lib/mysql"
      # - "/rendu-env/dockers/mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      inner:
        aliases:
          - MYSQL_URL
 
    # command: --init-file /docker-entrypoint-initdb.d/init.sql

